; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
; uncomment only one
; default_envs = elecrow-c3-128 


[env]
lib_deps = 
	lvgl/lvgl@9.5.0
	navio_ui=https://github.com/lvgl-pro-projects/fbiego--navio_ui
build_flags = 
    -I include
	-D LV_CONF_SKIP
    -D LV_CONF_INCLUDE_SIMPLE
	-D LV_LVGL_H_INCLUDE_SIMPLE=1
	-D LV_USE_OBJ_NAME=1
	-D LV_USE_STDLIB_MALLOC=LV_STDLIB_CLIB

	-D LV_USE_TRANSLATION=1
	-D LV_USE_TINY_TTF=1
    -D LV_USE_OS=LV_OS_CUSTOM
    -D LV_OS_CUSTOM_INCLUDE=\"lv_os_custom.h\"


[esp32]
platform = espressif32@6.9.0
framework = arduino
extra_scripts = 
	pre:scripts/board_profile_deps.py
	scripts/build_firmware.py
lib_deps = 
	${env.lib_deps}
	lovyan03/LovyanGFX@1.1.16
    fbiego/ChronosESP32@1.9.0
    fbiego/Timber@2.0.0
build_flags = 
	${env.build_flags}

	

; ELECROW C3 LCD 1.28
[env:elecrow-c3-128]
extends = esp32
board = lolin_c3_mini
board_build.partitions = partitions/partition.csv
lib_deps = 
	${esp32.lib_deps}
	makuna/RTC@2.4.3
build_flags = 
	${esp32.build_flags}
	-D BOARD_PROFILE_INCLUDE=\"boards/elecrow-c3-128.hpp\"

; Viewe SmartRing 466x466 AMOLED 
[env:viewe-smartring]
extends = esp32
board = lolin_s3_pro
board_build.partitions = partitions/partition_16M.csv
lib_deps = 
	${esp32.lib_deps}
	moononournation/GFX Library for Arduino@1.5.7
	lewisxhe/SensorLib@0.3.1
	FastIMU=https://github.com/LiquidCGS/FastIMU/archive/refs/tags/1.2.6.zip
build_flags = 
	${esp32.build_flags}
	-D BOARD_PROFILE_INCLUDE=\"boards/viewe-smartring.hpp\"
	-DARDUINO_USB_CDC_ON_BOOT=1

; Viewe Touch Knob 466x466 AMOLED 
[env:viewe-knob-15]
extends = esp32
board = lolin_s3_pro
board_build.partitions = partitions/partition_16M.csv
lib_deps = 
	${esp32.lib_deps}
	moononournation/GFX Library for Arduino@1.5.7
	lewisxhe/SensorLib@0.3.1
	paulstoffregen/Encoder@1.4.4
build_flags = 
	${esp32.build_flags}
	-D BOARD_PROFILE_INCLUDE=\"boards/viewe-knob-15.hpp\"

; Viewe S3 Round 1.5 466x466 AMOLED
[env:viewe-s3-15]
extends = esp32
board = lolin_s3_pro
board_build.partitions = partitions/partition_16M.csv
lib_deps = 
	${esp32.lib_deps}
	moononournation/GFX Library for Arduino@1.5.7
	lewisxhe/SensorLib@0.3.1
build_flags = 
	${esp32.build_flags}
	-D BOARD_PROFILE_INCLUDE=\"boards/viewe-s3-15.hpp\"
    -D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1


; Viewe Echo Ear 360x360 QSPI LCD
[env:viewe-echo-ear]
extends = esp32
board = lolin_s3_pro
board_build.partitions = partitions/partition_16M.csv
lib_deps = 
	${esp32.lib_deps}
	moononournation/GFX Library for Arduino@1.5.7
	lewisxhe/SensorLib@0.3.1
build_flags = 
	${esp32.build_flags}
	-D BOARD_PROFILE_INCLUDE=\"boards/viewe-echo-ear.hpp\"
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1

; Viewe Knob 1.28 240x240 LCD
[env:viewe-knob-128]
extends = esp32
board = lolin_c3_mini
board_build.partitions = partitions/partition.csv
lib_deps = 
	${esp32.lib_deps}
	lennarthennigs/Button2@2.3.2
build_flags = 
	${esp32.build_flags}
	-D BOARD_PROFILE_INCLUDE=\"boards/viewe-knob-128.hpp\"

; Viewe S3 2.8 240x320 LCD
[env:viewe-s3-28]
extends = esp32
board = lolin_s3_pro
board_build.partitions = partitions/partition_16M.csv
lib_deps = 
	${esp32.lib_deps}
	moononournation/GFX Library for Arduino@1.5.7
	lewisxhe/SensorLib@0.3.1
build_flags = 
	${esp32.build_flags}
	-D BOARD_PROFILE_INCLUDE=\"boards/viewe-s3-28.hpp\"
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1

; M5 Stack Dial
[env:m5-dial]
extends = esp32
board = m5stack-stamps3
board_build.partitions = partitions/partition_8M.csv
lib_deps = 
	${env.lib_deps}
    fbiego/ChronosESP32@1.9.0
    fbiego/Timber@2.0.0
	m5stack/M5Dial@1.0.3
build_flags = 
	${esp32.build_flags}
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D BOARD_PROFILE_INCLUDE=\"boards/m5-dial.hpp\"

; M5 Stack Core Basic
[env:m5-core-basic]
extends = esp32
board = m5stack-core-esp32
board_build.partitions = partitions/partition_16M.csv
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.flash_mode = dio
board_build.f_flash = 80000000L
lib_deps = 
	${env.lib_deps}
    fbiego/ChronosESP32@1.9.0
    fbiego/Timber@2.0.0
	m5stack/M5Unified@0.2.14
build_flags = 
	${esp32.build_flags}
	-D BOARD_PROFILE_INCLUDE=\"boards/m5-core-basic.hpp\"

; M5 Stack Core S3 Lite
[env:m5-core-s3-lite]
extends = esp32
board = lolin_s3_pro
board_build.partitions = partitions/partition_16M.csv
lib_deps = 
	${env.lib_deps}
    fbiego/ChronosESP32@1.9.0
    fbiego/Timber@2.0.0
	m5stack/M5Unified@0.2.14
build_flags = 
	${esp32.build_flags}
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D BOARD_PROFILE_INCLUDE=\"boards/m5-core-s3.hpp\"

; M5 Stack Core S3 SE
[env:m5-core-s3-se]
extends = esp32
board = lolin_s3_pro
board_build.partitions = partitions/partition_16M.csv
lib_deps = 
	${env.lib_deps}
    fbiego/ChronosESP32@1.9.0
    fbiego/Timber@2.0.0
	m5stack/M5Unified@0.2.14
build_flags = 
	${esp32.build_flags}
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D BOARD_PROFILE_INCLUDE=\"boards/m5-core-s3.hpp\"

; M5 Stack Cardputer
[env:m5-cardputer]
extends = esp32
board = m5stack-stamps3
board_build.partitions = partitions/partition_8M.csv
lib_deps = 
	${env.lib_deps}
    fbiego/ChronosESP32@1.9.0
    fbiego/Timber@2.0.0
	m5stack/M5Cardputer@1.1.1
build_flags = 
	${esp32.build_flags}
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D BOARD_PROFILE_INCLUDE=\"boards/m5-cardputer.hpp\"

; M5 Stack Cardputer Adv
[env:m5-cardputer-adv]
extends = esp32
board = m5stack-stamps3
board_build.partitions = partitions/partition_8M.csv
lib_deps = 
	${env.lib_deps}
    fbiego/ChronosESP32@1.9.0
    fbiego/Timber@2.0.0
	m5stack/M5Cardputer@1.1.1
build_flags = 
	${esp32.build_flags}
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D BOARD_PROFILE_INCLUDE=\"boards/m5-cardputer.hpp\"

; M5 Stack Stick C
[env:m5-stick-c]
extends = esp32
board = m5stick-c
board_build.partitions = partitions/partition.csv
lib_deps = 
	${env.lib_deps}
    fbiego/ChronosESP32@1.9.0
    fbiego/Timber@2.0.0
	m5stack/M5Unified@0.2.14
build_flags = 
	${esp32.build_flags}
	-D BOARD_PROFILE_INCLUDE=\"boards/m5-stick-c.hpp\"

; M5 Stack Atom S3R
[env:m5-atom-s3r]
extends = esp32
board = m5stack-atoms3
board_build.partitions = partitions/partition_8M.csv
lib_deps = 
	${env.lib_deps}
    fbiego/ChronosESP32@1.9.0
    fbiego/Timber@2.0.0
	m5stack/M5Unified@0.2.14
build_flags = 
	${esp32.build_flags}
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D BOARD_PROFILE_INCLUDE=\"boards/m5-atom-s3r.hpp\"

; Guition C3 1.28 Inch 240x240
[env:guition-2424s012]
extends = esp32
board = lolin_c3_mini
board_build.partitions = partitions/partition.csv
lib_deps = ${esp32.lib_deps}
build_flags = 
	${esp32.build_flags}
	-D BOARD_PROFILE_INCLUDE=\"boards/guition-2424s012.hpp\"

; Guition CYD 2.8 Inch
[env:guition-2432s028r]
extends = esp32
board = esp32doit-devkit-v1
board_build.partitions = partitions/partition.csv
lib_deps = ${esp32.lib_deps}
build_flags = 
	${esp32.build_flags}
	-D BOARD_PROFILE_INCLUDE=\"boards/guition-2432s028r.hpp\"

; Waveshare ESP32-S3-Touch-LCD-1.28
[env:waveshare-s3-lcd-128]
extends = esp32
board = lolin_s3_mini
board_upload.flash_size = 16MB
board_build.flash_mode = dio
board_build.f_flash = 80000000L
board_build.partitions = partitions/partition_16M.csv
lib_deps = 
	${esp32.lib_deps}
	FastIMU=https://github.com/LiquidCGS/FastIMU/archive/refs/tags/1.2.6.zip
build_flags = 
	${esp32.build_flags}
	-D BOARD_PROFILE_INCLUDE=\"boards/waveshare-s3-lcd-128.hpp\"

; Waveshare ESP32-S3-Touch-LCD-1.69
[env:waveshare-s3-lcd-169]
extends = esp32
board = esp32-s3-devkitc-1
board_upload.flash_size = 16MB
board_build.flash_mode = dio
board_build.f_flash = 80000000L
board_build.partitions = partitions/partition_16M.csv ; app3M_fat9M_16MB.csv
lib_deps = 
	${esp32.lib_deps}
	FastIMU=https://github.com/LiquidCGS/FastIMU/archive/refs/tags/1.2.6.zip
build_flags = 
	${esp32.build_flags}
	-D BOARD_PROFILE_INCLUDE=\"boards/waveshare-s3-lcd-169.hpp\"

; ESP32-S3-Touch-AMOLED-2.06
[env:waveshare-s3-amoled-206]
extends = esp32
board = lolin_s3_pro
board_build.partitions = partitions/partition_16M.csv
lib_deps = 
	${esp32.lib_deps}
	moononournation/GFX Library for Arduino@1.5.7
	lewisxhe/SensorLib@0.3.1
	FastIMU=https://github.com/LiquidCGS/FastIMU/archive/refs/tags/1.2.6.zip
build_flags = 
	${esp32.build_flags}
	-D BOARD_PROFILE_INCLUDE=\"boards/waveshare-s3-amoled-206.hpp\"
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1

; Webscreen HW Media Lab
[env:hwlab-webscreen]
extends = esp32
board = lolin_s3_pro
board_build.partitions = partitions/partition_16M.csv
lib_deps = 
	${esp32.lib_deps}
	moononournation/GFX Library for Arduino@1.5.7
build_flags = 
	${esp32.build_flags}
	-D BOARD_PROFILE_INCLUDE=\"boards/hwlab-webscreen.hpp\"
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1


